export const Productos = [{
    id: 1,
    name: 'Aceite de Ajedrea',
    type: 'Aceite',
    thumbnail:'../../assets/aceite-esencial-ajedrea.jpg',
    origin: 'Madagasacar',
    botanicName:'Satureja montana Oil',
},
{
    id: 2,
    name: 'Aceite de Albahaca',
    type: 'Aceite - Crema',
    thumbnail:'../../assets/aceite-esencial-albahaca.jpg',
    origin: 'Sudafrica',
    botanicName:'Ocimum basilicum Oil',
},
{
    id: 3,
    name: 'Aceite de Jengibre',
    type: 'Aceite - Gotas',
    thumbnail:'../../assets/aceite-esencial-jengibre-1.jpg',
    origin: 'India',
    botanicName:'Zingiber officinalis Oil',
},
{
    id: 4,
    name: 'Aceite de Limon',
    type: 'Aceite - Gotas',
    thumbnail:'../../assets/aceite-esencial-limon-1.jpg',
    origin: 'Uruguay',
    botanicName:'Citrus limonum Oil',
},
{
    id: 5,
    name: 'Aceite de Mandarina',
    type: 'Aceite',
    thumbnail:'../../assets/aceite-esencial-mandarina-1.jpg',
    origin: 'Brasil',
    botanicName:' Citrus reticulata Oil',
},
{
    id: 6,
    name: 'Aceite de Manzanilla',
    type: 'Aceite',
    thumbnail:'../../assets/aceite-esencial-manzanilla-1.jpg',
    origin: 'España',
    botanicName:'Santolina chamaecyparissus',
},]; 